drawer:
  color_palette:
  - - 0
    - 0
    - 255
  - - 255
    - 0
    - 0
  - - 255
    - 0
    - 255
  - - 0
    - 165
    - 255
  - - 0
    - 255
    - 255
  line_thickness: 2
  line_type: LINE_AA
